In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
indicators = pd.DataFrame({
    "sub_index": [
        "Economic", "Economic", "Economic",
        "Health", "Health", "Health",
        "Education", "Education", "Education",
        "Environment", "Environment", "Environment",
        "Living Conditions", "Living Conditions", "Living Conditions"
    ],
    
    "indicator": [
        "GDP per capita in PPS",
        "Employment rate",
        "At-risk-of-poverty rate",
        
        "Life expectancy at birth",
        "Healthy life years",
        "Self-perceived good or very good health",
        
        "Tertiary education attainment",
        "Early leavers from education and training",
        "Employment rate of recent graduates",
        
        "Renewable energy share",
        "Recycling rate of municipal waste",
        "Pollution, grime or environmental problems",
        
        "Housing cost overburden",
        "Household internet access",
        "Overall life satisfaction"
    ],
    
    "direction": [
        "positive", "positive", "negative",
        "positive", "positive", "positive",
        "positive", "negative", "positive",
        "positive", "positive", "negative",
        "negative", "positive", "positive"
    ]
})
indicators

            sub_index                                   indicator direction
0            Economic                       GDP per capita in PPS  positive
1            Economic                             Employment rate  positive
2            Economic                     At-risk-of-poverty rate  negative
3              Health                    Life expectancy at birth  positive
4              Health                          Healthy life years  positive
5              Health     Self-perceived good or very good health  positive
6           Education               Tertiary education attainment  positive
7           Education   Early leavers from education and training  negative
8           Education         Employment rate of recent graduates  positive
9         Environment                      Renewable energy share  positive
10        Environment           Recycling rate of municipal waste  positive
11        Environment  Pollution, grime or environmental problems  negative
12  Living Conditions                     Housing cost overburden  negative
13  Living Conditions                   Household internet access  positive
14  Living Conditions                   Overall life satisfaction  positive

# Reading the needed files

In [4]:
self_perceived_health = pd.read_csv("../data/raw/self_perceived_health.csv")
early_leavers_from_education = pd.read_csv("../data/raw/early_leavers_from_education.csv")
employment_rate_post_grad = pd.read_csv("../data/raw/employment_rate_post_grad.csv")
environmental_problems = pd.read_csv("../data/raw/environmental_problems.csv")
household_internet_access = pd.read_csv("../data/raw/household_internet_access.csv")
housing_cost_overburden = pd.read_csv("../data/raw/housing_cost_overburden.csv")
overall_life_satisfaction = pd.read_csv("../data/raw/overall_life_satisfaction.csv")
recycling_rate = pd.read_csv("../data/raw/recycling_rate.csv")
renewable_energy_share = pd.read_csv("../data/raw/renewable_energy_share.csv")

# Economy Indicator

## GDP per Capita

In [5]:
gdp = pd.read_csv("../data/raw/gdp_per_capita_pps.csv")

gdp.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,indic_ppp,Purchasing power parities indicator,ppp_cat18,Analytical categories for purchasing power parities (PPPs) calculation (based on COICOP18),geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,AL,Albania,2014,NaN,30,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,AL,Albania,2015,NaN,30,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,AL,Albania,2016,NaN,30,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,AL,Albania,2017,NaN,30,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,AL,Albania,2018,NaN,30,NaN,NaN,NaN,NaN,NaN

In [6]:
gdp_2024 = gdp[gdp["TIME_PERIOD"] == 2024].copy()

gdp_2024.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,indic_ppp,Purchasing power parities indicator,ppp_cat18,Analytical categories for purchasing power parities (PPPs) calculation (based on COICOP18),geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
10,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,AL,Albania,2024,NaN,42,NaN,NaN,NaN,NaN,NaN
22,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,AT,Austria,2024,NaN,119,NaN,NaN,NaN,NaN,NaN
34,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,BA,Bosnia and Herzegovina,2024,NaN,37,NaN,NaN,NaN,NaN,NaN
46,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,BE,Belgium,2024,NaN,117,NaN,NaN,NaN,NaN,NaN
58,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,BG,Bulgaria,2024,NaN,66,NaN,NaN,NaN,NaN,NaN

In [7]:
gdp_2024[[
    "geo",
    "Geopolitical entity (reporting)",
    "TIME_PERIOD",
    "OBS_VALUE"
]].head(15)

      geo        Geopolitical entity (reporting)  TIME_PERIOD  OBS_VALUE
10     AL                                Albania         2024         42
22     AT                                Austria         2024        119
34     BA                 Bosnia and Herzegovina         2024         37
46     BE                                Belgium         2024        117
58     BG                               Bulgaria         2024         66
70     CH                            Switzerland         2024        157
82     CY                                 Cyprus         2024         99
94     CZ                                Czechia         2024         90
106    DE                                Germany         2024        116
118    DK                                Denmark         2024        127
130  EA19  Euro area - 19 countries  (2015-2022)         2024        105
142  EA20   Euro area – 20 countries (2023-2025)         2024        104
154  EA21   Euro area – 21 countries (from 2026)         2024        104
166    EE                                Estonia         2024         79
178    EL                                 Greece         2024         68

In [8]:
eu27 = [
    "AT", "BE", "BG", "HR", "CY", "CZ", "DK",
    "EE", "FI", "FR", "DE", "EL", "HU", "IE",
    "IT", "LV", "LT", "LU", "MT", "NL", "PL",
    "PT", "RO", "SK", "SI", "ES", "SE"
]

In [9]:
gdp_eu27 = gdp_2024[gdp_2024["geo"].isin(eu27)].copy()

gdp_eu27[[
    "geo",
    "Geopolitical entity (reporting)",
    "TIME_PERIOD",
    "OBS_VALUE"
]].head()

   geo Geopolitical entity (reporting)  TIME_PERIOD  OBS_VALUE
22  AT                         Austria         2024        119
46  BE                         Belgium         2024        117
58  BG                        Bulgaria         2024         66
82  CY                          Cyprus         2024         99
94  CZ                         Czechia         2024         90

In [10]:
gdp_eu27.shape

(27, 19)

In [11]:
gdp_eu27["geo"].nunique()

27

In [12]:
missing_countries = set(eu27) - set(gdp_eu27["geo"])

missing_countries

set()

In [13]:
gdp_2024.shape

(43, 19)

In [14]:
gdp.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency',
       'indic_ppp', 'Purchasing power parities indicator', 'ppp_cat18',
       'Analytical categories for purchasing power parities (PPPs) calculation (based on COICOP18)',
       'geo', 'Geopolitical entity (reporting)', 'TIME_PERIOD', 'Time',
       'OBS_VALUE', 'Observation value', 'OBS_FLAG',
       'Observation status (Flag) V2 structure', 'CONF_STATUS',
       'Confidentiality status (flag)'],
      dtype='str')

In [15]:
gdp_clean = gdp_eu27[
    ["geo", "Geopolitical entity (reporting)", "TIME_PERIOD", "OBS_VALUE"]
].copy()

gdp_clean.head()

   geo Geopolitical entity (reporting)  TIME_PERIOD  OBS_VALUE
22  AT                         Austria         2024        119
46  BE                         Belgium         2024        117
58  BG                        Bulgaria         2024         66
82  CY                          Cyprus         2024         99
94  CZ                         Czechia         2024         90

In [16]:
gdp_clean = gdp_clean.rename(columns={
    "geo": "country_code",
    "Geopolitical entity (reporting)": "country_name",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "gdp_per_capita_pps"
})

gdp_clean.head()

   country_code country_name  year  gdp_per_capita_pps
22           AT      Austria  2024                 119
46           BE      Belgium  2024                 117
58           BG     Bulgaria  2024                  66
82           CY       Cyprus  2024                  99
94           CZ      Czechia  2024                  90

In [17]:
gdp_clean.shape

(27, 4)

In [18]:
gdp_clean.isnull().sum()

country_code          0
country_name          0
year                  0
gdp_per_capita_pps    0
dtype: int64

In [19]:
gdp_clean.nsmallest(5, "gdp_per_capita_pps")
gdp_clean.nlargest(5, "gdp_per_capita_pps")

    country_code country_name  year  gdp_per_capita_pps
322           LU   Luxembourg  2024                 244
262           IE      Ireland  2024                 221
382           NL  Netherlands  2024                 134
118           DK      Denmark  2024                 127
22            AT      Austria  2024                 119

In [20]:
gdp_clean.to_csv("../data/processed/gdp_clean.csv", index=False)

## Employment Rate

In [21]:
employment = pd.read_csv("../data/raw/employment_rate.csv")

employment.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,indic_em,Employment indicator,sex,Sex,age,Age class,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:TIPSLM100(1.0),Employment rate,A,Annual,EMP_LFS,Total employment (resident population concept ...,T,Total,Y20-64,From 20 to 64 years,PC_POP,Percentage of total population,AT,Austria,2009,NaN,73.4,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:TIPSLM100(1.0),Employment rate,A,Annual,EMP_LFS,Total employment (resident population concept ...,T,Total,Y20-64,From 20 to 64 years,PC_POP,Percentage of total population,AT,Austria,2010,NaN,73.9,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:TIPSLM100(1.0),Employment rate,A,Annual,EMP_LFS,Total employment (resident population concept ...,T,Total,Y20-64,From 20 to 64 years,PC_POP,Percentage of total population,AT,Austria,2011,NaN,74.2,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:TIPSLM100(1.0),Employment rate,A,Annual,EMP_LFS,Total employment (resident population concept ...,T,Total,Y20-64,From 20 to 64 years,PC_POP,Percentage of total population,AT,Austria,2012,NaN,74.4,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:TIPSLM100(1.0),Employment rate,A,Annual,EMP_LFS,Total employment (resident population concept ...,T,Total,Y20-64,From 20 to 64 years,PC_POP,Percentage of total population,AT,Austria,2013,NaN,74.6,NaN,NaN,NaN,NaN,NaN

In [22]:
employment.shape
employment.columns
employment.info()

<class 'pandas.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 23 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   STRUCTURE                               520 non-null    str
 1   STRUCTURE_ID                            520 non-null    str
 2   STRUCTURE_NAME                          520 non-null    str
 3   freq                                    520 non-null    str
 4   Time frequency                          520 non-null    str
 5   indic_em                                520 non-null    str
 6   Employment indicator                    520 non-null    str
 7   sex                                     520 non-null    str
 8   Sex                                     520 non-null    str
 9   age                                     520 non-null    str
 10  Age class                               520 non-null    str
 11  unit                                    520 non-null    str
 12  Unit of measure                         520 non-null    str
 13  geo                                     520 non-null    str
 14  Geopolitical entity (reporting)         520 non-null    str
 15  TIME_PERIOD                             520 non-null    int64
 16  Time                                    0 non-null      float64
 17  OBS_VALUE                               520 non-null    float64
 18  Observation value                       0 non-null      float64
 19  OBS_FLAG                                29 non-null     str
 20  Observation status (Flag) V2 structure  29 non-null     str
 21  CONF_STATUS                             0 non-null      float64
 22  Confidentiality status (flag)           0 non-null      float64
dtypes: float64(5), int64(1), str(17)
memory usage: 93.6 KB

In [23]:
employment_2024 = employment[employment["TIME_PERIOD"] == 2024].copy()
employment_2024.shape

(30, 23)

In [24]:
employment_eu27 = employment_2024[employment_2024["geo"].isin(eu27)].copy()

employment_eu27.shape

(27, 23)

In [25]:
employment_clean = employment_eu27[
    [
        "geo", "Geopolitical entity (reporting)", "TIME_PERIOD", "OBS_VALUE"
    ]
].copy()

In [26]:
employment_clean = employment_clean.rename(columns={
    "geo": "country_code",
    "Geopolitical entity (reporting)": "country_name",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "employment_rate"
})

In [27]:
employment_clean = (
    employment_clean.sort_values("country_name").reset_index(drop=True))

employment_clean.head()

  country_code country_name  year  employment_rate
0           AT      Austria  2024             77.4
1           BE      Belgium  2024             72.3
2           BG     Bulgaria  2024             76.8
3           HR      Croatia  2024             73.6
4           CY       Cyprus  2024             80.1

In [28]:
employment_clean.isnull().sum()

country_code       0
country_name       0
year               0
employment_rate    0
dtype: int64

In [29]:
employment_clean.to_csv("../data/processed/employment_clean.csv", index=False)

### Merging GDP and Employment

In [30]:
eqli_data = pd.merge(
    gdp_clean[["country_code", "country_name",  "gdp_per_capita_pps"]],
    employment_clean[["country_code", "employment_rate"]],

    on="country_code",
    how="inner"

)

eqli_data.head()

  country_code country_name  gdp_per_capita_pps  employment_rate
0           AT      Austria                 119             77.4
1           BE      Belgium                 117             72.3
2           BG     Bulgaria                  66             76.8
3           CY       Cyprus                  99             80.1
4           CZ      Czechia                  90             82.3

In [31]:
eqli_data.shape
eqli_data.isnull().sum()

country_code          0
country_name          0
gdp_per_capita_pps    0
employment_rate       0
dtype: int64

In [32]:
eqli_data[["country_name", "gdp_per_capita_pps", "employment_rate"]].head(10)

  country_name  gdp_per_capita_pps  employment_rate
0      Austria                 119             77.4
1      Belgium                 117             72.3
2     Bulgaria                  66             76.8
3       Cyprus                  99             80.1
4      Czechia                  90             82.3
5      Germany                 116             81.1
6      Denmark                 127             80.2
7      Estonia                  79             81.8
8       Greece                  68             69.3
9        Spain                  91             71.4

In [33]:
eqli_data["country_code"].nunique()

27

In [34]:
set(eu27) - set(eqli_data["country_code"])

set()

In [35]:
eqli_data.to_csv(
    "../data/processed/eqli_master.csv",
    index=False
)

## Poverty Rate

In [36]:
poverty = pd.read_csv("../data/raw/poverty_rate.csv")

poverty.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,sex,Sex,unit,Unit of measure,statinfo,Statistical information,rskpovth,Risk of poverty threshold,age,Age class,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:TIPSLC20(1.0),People at risk of poverty after social transfer,A,Annual,T,Total,PC,Percentage,MED_EI,Median equivalised income,B_60,Below 60%,TOTAL,Total,AT,Austria,1995,NaN,13.0,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:TIPSLC20(1.0),People at risk of poverty after social transfer,A,Annual,T,Total,PC,Percentage,MED_EI,Median equivalised income,B_60,Below 60%,TOTAL,Total,AT,Austria,1996,NaN,14.0,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:TIPSLC20(1.0),People at risk of poverty after social transfer,A,Annual,T,Total,PC,Percentage,MED_EI,Median equivalised income,B_60,Below 60%,TOTAL,Total,AT,Austria,1997,NaN,13.0,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:TIPSLC20(1.0),People at risk of poverty after social transfer,A,Annual,T,Total,PC,Percentage,MED_EI,Median equivalised income,B_60,Below 60%,TOTAL,Total,AT,Austria,1998,NaN,13.0,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:TIPSLC20(1.0),People at risk of poverty after social transfer,A,Annual,T,Total,PC,Percentage,MED_EI,Median equivalised income,B_60,Below 60%,TOTAL,Total,AT,Austria,1999,NaN,12.0,NaN,NaN,NaN,NaN,NaN

In [37]:
poverty_2024 = poverty[poverty["TIME_PERIOD"] == 2024].copy()

poverty_2024.shape

(28, 25)

In [38]:
poverty_eu27 = poverty_2024[poverty_2024["geo"].isin(eu27)].copy()

poverty_eu27.shape

(27, 25)

In [39]:
poverty_clean = poverty_eu27[[
    "geo", "Geopolitical entity (reporting)", "TIME_PERIOD", "OBS_VALUE"
]].copy()

In [40]:
poverty_clean = poverty_clean.rename(columns={
    "geo": "country_code",
    "Geopolitical entity (reporting)": "country_name",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "poverty_rate"})

In [41]:
poverty_clean = (poverty_clean .sort_values("country_name").reset_index(drop=True))

poverty_clean.head()

  country_code country_name  year  poverty_rate
0           AT      Austria  2024          14.3
1           BE      Belgium  2024          11.4
2           BG     Bulgaria  2024          21.7
3           HR      Croatia  2024          20.3
4           CY       Cyprus  2024          14.6

In [42]:
poverty_clean.shape

(27, 4)

In [43]:
poverty_clean.isnull().sum()

country_code    0
country_name    0
year            0
poverty_rate    0
dtype: int64

In [44]:
eqli_data = pd.merge(
    eqli_data,
    poverty_clean[
        ["country_code", "poverty_rate"]
    ],
    on="country_code",
    how="inner"
)

eqli_data.head()

  country_code country_name  gdp_per_capita_pps  employment_rate  poverty_rate
0           AT      Austria                 119             77.4          14.3
1           BE      Belgium                 117             72.3          11.4
2           BG     Bulgaria                  66             76.8          21.7
3           CY       Cyprus                  99             80.1          14.6
4           CZ      Czechia                  90             82.3           9.5

In [45]:
eqli_data.shape

(27, 5)

In [46]:
eqli_data.to_csv(
    "../data/processed/eqli_master.csv",
    index=False
)

# Health Indicator

## Life expectancy

In [127]:
life_expectancy = pd.read_csv(
    "../data/raw/life_expectancy.csv"
)

life_expectancy.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,sex,Sex,age,Age class,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:TPS00205(1.0),Life expectancy at birth by sex,A,Annual,YR,Year,T,Total,Y_LT1,Less than 1 year,AL,Albania,2013,NaN,77.9,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:TPS00205(1.0),Life expectancy at birth by sex,A,Annual,YR,Year,T,Total,Y_LT1,Less than 1 year,AL,Albania,2014,NaN,78.2,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:TPS00205(1.0),Life expectancy at birth by sex,A,Annual,YR,Year,T,Total,Y_LT1,Less than 1 year,AL,Albania,2015,NaN,77.9,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:TPS00205(1.0),Life expectancy at birth by sex,A,Annual,YR,Year,T,Total,Y_LT1,Less than 1 year,AL,Albania,2016,NaN,78.5,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:TPS00205(1.0),Life expectancy at birth by sex,A,Annual,YR,Year,T,Total,Y_LT1,Less than 1 year,AL,Albania,2017,NaN,78.5,NaN,NaN,NaN,NaN,NaN

In [128]:
life_expectancy_2024 = life_expectancy[
    life_expectancy["TIME_PERIOD"] == 2024
].copy()

life_expectancy_2024.shape

(39, 21)

In [129]:
life_expectancy_eu27 = life_expectancy_2024[
    life_expectancy_2024["geo"].isin(eu27)
].copy()

life_expectancy_eu27.shape

(27, 21)

In [130]:
life_expectancy_clean = life_expectancy_eu27[
    [
        "geo",
        "Geopolitical entity (reporting)",
        "TIME_PERIOD",
        "OBS_VALUE"
    ]
].copy()

In [131]:
life_expectancy_clean = life_expectancy_clean.rename(columns={
    "geo": "country_code",
    "Geopolitical entity (reporting)": "country",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "life_expectancy"
})

In [132]:
life_expectancy_clean = (
    life_expectancy_clean
    .sort_values("country")
    .reset_index(drop=True)
)

life_expectancy_clean.head()

  country_code   country  year  life_expectancy
0           AT   Austria  2024             82.1
1           BE   Belgium  2024             82.4
2           BG  Bulgaria  2024             75.8
3           HR   Croatia  2024             78.9
4           CY    Cyprus  2024             83.5

In [133]:
life_expectancy_clean.shape

(27, 4)

In [134]:
life_expectancy_clean.isnull().sum()

country_code       0
country            0
year               0
life_expectancy    0
dtype: int64

In [135]:
eqli_data = pd.merge(
    eqli_data,
    life_expectancy_clean[
        ["country_code", "life_expectancy"]
    ],
    on="country_code",
    how="inner"
)

eqli_data.head()

,country_code,country_name,gdp_per_capita_pps,employment_rate,poverty_rate,life_expectancy_x,healthy_life_years,self_perceived_health,tertiary_education_attainment_x,early_leavers_x,tertiary_education_attainment_y,early_leavers_y,life_expectancy_y
0,AT,Austria,119,77.4,14.3,82.1,60.4,67.7,44.1,8.1,44.1,8.1,82.1
1,BE,Belgium,117,72.3,11.4,82.4,63.9,74.6,50.7,7.0,50.7,7.0,82.4
2,BG,Bulgaria,66,76.8,21.7,75.8,69.1,65.7,40.5,8.2,40.5,8.2,75.8
3,CY,Cyprus,99,80.1,14.6,83.5,63.9,75.2,60.3,11.4,60.3,11.4,83.5
4,CZ,Czechia,90,82.3,9.5,80.1,62.4,66.4,33.5,5.4,33.5,5.4,80.1

In [136]:
eqli_data.shape

(27, 13)

In [137]:
life_expectancy_clean.to_csv(
    "../data/processed/life_expectancy_2024.csv",
    index=False
)

In [138]:
eqli_data.to_csv(
    "../data/processed/eqli_master.csv",
    index=False
)

## Healthy Life Years

In [139]:
healthy_life = pd.read_csv("../data/raw/healthy_life_years.csv")

healthy_life.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,sex,Sex,hlth_hle,Health and life expectancy,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:TPS00150(1.0),Healthy life years at birth by sex,A,Annual,YR,Year,T,Total,HLY_Y0,Healthy life years in absolute value at birth,AT,Austria,2013,NaN,59.9,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:TPS00150(1.0),Healthy life years at birth by sex,A,Annual,YR,Year,T,Total,HLY_Y0,Healthy life years in absolute value at birth,AT,Austria,2014,NaN,57.7,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:TPS00150(1.0),Healthy life years at birth by sex,A,Annual,YR,Year,T,Total,HLY_Y0,Healthy life years in absolute value at birth,AT,Austria,2015,NaN,58.0,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:TPS00150(1.0),Healthy life years at birth by sex,A,Annual,YR,Year,T,Total,HLY_Y0,Healthy life years in absolute value at birth,AT,Austria,2016,NaN,57.0,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:TPS00150(1.0),Healthy life years at birth by sex,A,Annual,YR,Year,T,Total,HLY_Y0,Healthy life years in absolute value at birth,AT,Austria,2017,NaN,57.1,NaN,NaN,NaN,NaN,NaN

In [140]:
healthy_life_2024 = healthy_life[
    healthy_life["TIME_PERIOD"] == 2024
].copy()

healthy_life_2024.shape

(29, 21)

In [141]:
healthy_life_eu27 = healthy_life_2024[
    healthy_life_2024["geo"].isin(eu27)
].copy()

healthy_life_eu27.shape

(26, 21)

In [142]:
# checking missing values
missing_countries = set(eu27) - set(healthy_life_eu27["geo"])

missing_countries

{'LU'}

In [143]:
healthy_life[
    healthy_life["geo"] == "LU"
][
    [
        "geo",
        "Geopolitical entity (reporting)",
        "TIME_PERIOD",
        "OBS_VALUE"
    ]
]

    geo Geopolitical entity (reporting)  TIME_PERIOD  OBS_VALUE
233  LU                      Luxembourg         2013       63.3
234  LU                      Luxembourg         2014       63.8
235  LU                      Luxembourg         2015       62.2
236  LU                      Luxembourg         2016       60.2
237  LU                      Luxembourg         2017       59.2
238  LU                      Luxembourg         2018       60.7
239  LU                      Luxembourg         2019       62.6
240  LU                      Luxembourg         2020       63.3
241  LU                      Luxembourg         2021       62.0
242  LU                      Luxembourg         2022       60.2

In [144]:
#Adding Luxembourg's 2022 value

lu_2022 = healthy_life[(healthy_life["geo"] == "LU") & (healthy_life["TIME_PERIOD"] == 2022)].copy()

lu_2022[
    [
        "geo",
        "Geopolitical entity (reporting)",
        "TIME_PERIOD",
        "OBS_VALUE"
    ]
]

    geo Geopolitical entity (reporting)  TIME_PERIOD  OBS_VALUE
242  LU                      Luxembourg         2022       60.2

In [145]:
healthy_life_updated = pd.concat([healthy_life_eu27, lu_2022], ignore_index=True)

In [146]:
healthy_life_updated.shape

(27, 21)

In [147]:
healthy_life_clean = healthy_life_updated[[
    "geo",
    "Geopolitical entity (reporting)",
    "TIME_PERIOD",
    "OBS_VALUE"
]]

In [148]:
healthy_life_clean = healthy_life_clean.rename(columns={
    "geo": "country_code",
    "Geopolitical entity (reporting)": "country_name",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "healthy_life_years"
})

In [149]:
healthy_life_clean = (healthy_life_clean.sort_values("country_name").reset_index(drop=True))

healthy_life_clean[healthy_life_clean["country_code"] == "LU"]

   country_code country_name  year  healthy_life_years
17           LU   Luxembourg  2022                60.2

In [150]:
healthy_life_clean.isnull().sum()

country_code          0
country_name          0
year                  0
healthy_life_years    0
dtype: int64

In [151]:
healthy_life_clean.shape

(27, 4)

In [152]:
eqli_data = pd.merge(
    eqli_data,
    healthy_life_clean[
        ["country_code", "healthy_life_years"]
    ],
    on="country_code",
    how="inner"
)

eqli_data.head()

,country_code,country_name,gdp_per_capita_pps,employment_rate,poverty_rate,life_expectancy_x,healthy_life_years_x,self_perceived_health,tertiary_education_attainment_x,early_leavers_x,tertiary_education_attainment_y,early_leavers_y,life_expectancy_y,healthy_life_years_y
0,AT,Austria,119,77.4,14.3,82.1,60.4,67.7,44.1,8.1,44.1,8.1,82.1,60.4
1,BE,Belgium,117,72.3,11.4,82.4,63.9,74.6,50.7,7.0,50.7,7.0,82.4,63.9
2,BG,Bulgaria,66,76.8,21.7,75.8,69.1,65.7,40.5,8.2,40.5,8.2,75.8,69.1
3,CY,Cyprus,99,80.1,14.6,83.5,63.9,75.2,60.3,11.4,60.3,11.4,83.5,63.9
4,CZ,Czechia,90,82.3,9.5,80.1,62.4,66.4,33.5,5.4,33.5,5.4,80.1,62.4

In [153]:
eqli_data.shape

(27, 14)

In [154]:
healthy_life_clean.to_csv(
    "../data/processed/healthy_life_years_clean.csv",
    index=False
)

eqli_data.to_csv(
    "../data/processed/eqli_master.csv",
    index=False
)

## Self Percieved Health

In [155]:
self_perceived_health_2024 = self_perceived_health[
    self_perceived_health["TIME_PERIOD"] == 2024
].copy()

self_perceived_health_2024.shape

KeyError: 'TIME_PERIOD'

In [ ]:
self_perceived_health_eu27 = self_perceived_health_2024[
    self_perceived_health_2024["geo"].isin(eu27)
].copy()

self_perceived_health_eu27.shape

(27, 25)

In [ ]:
self_perceived_health_eu27["geo"].nunique()

27

In [ ]:
self_perceived_health_clean = self_perceived_health_eu27[[
    "geo",
    "Geopolitical entity (reporting)",
    "TIME_PERIOD",
    "OBS_VALUE"
]].copy()

In [ ]:
self_perceived_health = self_perceived_health_clean.rename(columns={
    "geo": "country_code",
    "Geopolitical entity (reporting)": "country_name",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "self_perceived_health"
})

In [ ]:
self_perceived_health_clean = self_perceived_health_clean.rename(columns={
    "geo": "country_code",
    "Geopolitical entity (reporting)": "country_name",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "self_perceived_health"
}).sort_values("country_name").reset_index(drop=True)

self_perceived_health_clean.head()

  country_code country_name  year  self_perceived_health
0           AT      Austria  2024                   67.7
1           BE      Belgium  2024                   74.6
2           BG     Bulgaria  2024                   65.7
3           HR      Croatia  2024                   67.2
4           CY       Cyprus  2024                   75.2

In [ ]:
self_perceived_health_clean.isnull().sum()

country_code             0
country_name             0
year                     0
self_perceived_health    0
dtype: int64

In [ ]:
self_perceived_health_clean.shape

(27, 4)

In [ ]:
eqli_data = pd.merge(
    eqli_data,
    self_perceived_health_clean[
        ["country_code", "self_perceived_health"]
    ],
    on="country_code",
    how="inner"
)

In [ ]:
self_perceived_health_clean.to_csv(
    "../data/processed/self_perceived_health_clean.csv",
    index=False
)

eqli_data.to_csv(
    "../data/processed/eqli_master.csv",
    index=False
)

# Education Indicator

## Tertiary Education as a Health Indicator

In [106]:
tertiary_education = pd.read_csv("../data/raw/tertiary_education.csv")
tertiary_education.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,sex,Sex,age,Age class,unit,Unit of measure,isced11,International Standard Classification of Education (ISCED 2011),geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:SDG_04_20(1.0),Persons aged 25-34 with tertiary educational a...,A,Annual,T,Total,Y25-34,From 25 to 34 years,PC,Percentage,ED5-8,Tertiary education (levels 5-8),AT,Austria,2000,NaN,NaN,NaN,u,low reliability,NaN,NaN
1,dataflow,ESTAT:SDG_04_20(1.0),Persons aged 25-34 with tertiary educational a...,A,Annual,T,Total,Y25-34,From 25 to 34 years,PC,Percentage,ED5-8,Tertiary education (levels 5-8),AT,Austria,2001,NaN,NaN,NaN,u,low reliability,NaN,NaN
2,dataflow,ESTAT:SDG_04_20(1.0),Persons aged 25-34 with tertiary educational a...,A,Annual,T,Total,Y25-34,From 25 to 34 years,PC,Percentage,ED5-8,Tertiary education (levels 5-8),AT,Austria,2002,NaN,NaN,NaN,u,low reliability,NaN,NaN
3,dataflow,ESTAT:SDG_04_20(1.0),Persons aged 25-34 with tertiary educational a...,A,Annual,T,Total,Y25-34,From 25 to 34 years,PC,Percentage,ED5-8,Tertiary education (levels 5-8),AT,Austria,2003,NaN,NaN,NaN,u,low reliability,NaN,NaN
4,dataflow,ESTAT:SDG_04_20(1.0),Persons aged 25-34 with tertiary educational a...,A,Annual,T,Total,Y25-34,From 25 to 34 years,PC,Percentage,ED5-8,Tertiary education (levels 5-8),AT,Austria,2004,NaN,20.1,NaN,b,break in time series,NaN,NaN

In [107]:
tertiary_education_2024 = tertiary_education[
    tertiary_education["TIME_PERIOD"] == 2024].copy()

tertiary_education_2024.shape

(36, 23)

In [108]:
tertiary_education_eu27 = tertiary_education_2024[
    tertiary_education_2024["geo"].isin(eu27)
].copy()

tertiary_education_eu27.shape

(27, 23)

In [109]:
tertiary_education_clean = tertiary_education_eu27[[
    "geo",
    "Geopolitical entity (reporting)",
    "TIME_PERIOD",
    "OBS_VALUE"
]].copy()

In [110]:
tertiary_eduaction_clean = tertiary_education_clean.rename(columns={
    "geo": "country_code",
    "Geopolitical entity (reporting)": "country_name",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "tertiary_education_attainment"
})

tertiary_eduaction_clean = (tertiary_eduaction_clean.sort_values("country_name").reset_index(drop=True))

tertiary_eduaction_clean.head()

  country_code country_name  year  tertiary_education_attainment
0           AT      Austria  2024                           44.1
1           BE      Belgium  2024                           50.7
2           BG     Bulgaria  2024                           40.5
3           HR      Croatia  2024                           39.4
4           CY       Cyprus  2024                           60.3

In [111]:
tertiary_education_clean.isnull().sum()

geo                                0
Geopolitical entity (reporting)    0
TIME_PERIOD                        0
OBS_VALUE                          0
dtype: int64

In [112]:
#merge
eqli_data = pd.merge(
    eqli_data,
    tertiary_eduaction_clean[
        ["country_code", "tertiary_education_attainment"]
    ],
    on="country_code",
    how="inner"
)

eqli_data.shape

(27, 11)

In [113]:
tertiary_education_clean.to_csv(
    "../data/processed/tertiary_education_clean.csv",
    index=False
)

eqli_data.to_csv(
    "../data/processed/eqli_master.csv",
    index=False
)

## Early leavers from education

In [114]:
early_leavers_from_education_2024 = early_leavers_from_education[
    early_leavers_from_education["TIME_PERIOD"] == 2024
].copy()

early_leavers_from_education_2024.shape

(36, 23)

In [115]:
early_leavers_eu27 = early_leavers_from_education_2024[
    early_leavers_from_education_2024["geo"].isin(eu27)
].copy()

early_leavers_eu27.shape

(27, 23)

In [116]:
early_leavers_clean = early_leavers_eu27[[
    "geo",
    "Geopolitical entity (reporting)",
    "TIME_PERIOD",
    "OBS_VALUE"
]].copy()

In [117]:
early_leavers_clean = early_leavers_clean.rename(columns={
    "geo": "country_code",
    "Geopolitical entity (reporting)": "country_name",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "early_leavers"
})

In [118]:
early_leavers_clean = (early_leavers_clean.sort_values("country_name").reset_index(drop=True))

In [119]:
early_leavers_clean.isnull().sum()

country_code     0
country_name     0
year             0
early_leavers    0
dtype: int64

In [120]:
eqli_data = pd.merge(
    eqli_data,
    early_leavers_clean[
        ["country_code", "early_leavers"]
    ],
    on="country_code",
    how="inner"
)

eqli_data.shape

(27, 12)

In [121]:
early_leavers_clean.to_csv(
    "../data/processed/early_leavers_clean.csv", index=False)

eqli_data.to_csv(
    "../data/processed/eqli_master.csv",
    index=False
)

## Employment Rate of Recent Graduates

In [122]:
employment_rate_post_grad_2024 = employment_rate_post_grad[
    employment_rate_post_grad["TIME_PERIOD"] == 2024
].copy()

In [123]:
employment_rate_post_grad_eu27 = employment_rate_post_grad_2024[
    employment_rate_post_grad_2024["geo"].isin(eu27)
].copy()

employment_rate_post_grad_eu27.shape

(27, 25)

In [158]:
employment_rate_post_grad_clean = employment_rate_post_grad_eu27[
    [
        "geo",
        "Geopolitical entity (reporting)",
        "TIME_PERIOD",
        "OBS_VALUE"
    ]
].copy()

In [159]:
employment_rate_post_grad_clean = employment_rate_post_grad_clean.rename(columns={
    "geo": "country_code",
    "Geopolitical entity (reporting)": "country_name",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "recent_graduate_employment"
})

In [160]:
employment_rate_post_grad_clean = (employment_rate_post_grad_clean.sort_values("country_name").reset_index(drop=True))

In [161]:
employment_rate_post_grad_clean.isnull().sum()

country_code                  0
country_name                  0
year                          0
recent_graduate_employment    0
dtype: int64

In [162]:
eqli_data = pd.merge(
    eqli_data,
    employment_rate_post_grad_clean[
        ["country_code", "recent_graduate_employment"]
    ],
    on="country_code",
    how="inner"
)

eqli_data.shape

(27, 15)

In [163]:
employment_rate_post_grad_clean.to_csv(
    "../data/processed/employment_rate_post_grad_clean.csv",
    index=False
)

eqli_data.to_csv(
    "../data/processed/eqli_master.csv",
    index=False
)

# Environment Indicator

## Renewable Energy

In [164]:
renewable_energy_share_2024 = renewable_energy_share[
    renewable_energy_share["TIME_PERIOD"] == 2024
].copy()

renewable_energy_share_2024.shape

(38, 19)

In [165]:
renewable_energy_share_eu27 = renewable_energy_share_2024[
    renewable_energy_share_2024["geo"].isin(eu27)
].copy()

renewable_energy_share_eu27.shape

(27, 19)

In [166]:
renewable_energy_share_clean = renewable_energy_share_eu27[[
    "geo",
    "Geopolitical entity (reporting)",
    "TIME_PERIOD",
    "OBS_VALUE"
]].copy()

In [167]:
renewable_energy_share_clean = renewable_energy_share_clean.rename(columns={
    "geo": "country_code",
    "Geopolitical entity (reporting)": "country_name",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "renewable_energy_share"
})

In [168]:
renewable_energy_share_clean = (renewable_energy_share_clean.sort_values("country_name").reset_index(drop=True))

renewable_energy_share_clean.head()

  country_code country_name  year  renewable_energy_share
0           AT      Austria  2024                  42.951
1           BE      Belgium  2024                  14.336
2           BG     Bulgaria  2024                  23.210
3           HR      Croatia  2024                  26.477
4           CY       Cyprus  2024                  20.844

In [169]:
renewable_energy_share_clean.isnull().sum()

country_code              0
country_name              0
year                      0
renewable_energy_share    0
dtype: int64

In [170]:
eqli_data = pd.merge(
    eqli_data,
    renewable_energy_share_clean[
        ["country_code", "renewable_energy_share"]
    ],
    on="country_code",
    how="inner"
)

eqli_data.shape

(27, 16)

In [171]:
renewable_energy_share_clean.to_csv(
    "../data/processed/renewable_energy_share_clean.csv",
    index=False
)

eqli_data.to_csv(
    "../data/processed/eqli_master.csv",
    index=False
)

## Municipal Recycling

In [172]:
recycling_rate["TIME_PERIOD"].unique()

array([2020, 2021, 2022, 2023, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
       2018, 2019, 2024])

In [174]:
recycling_rate_2024 = recycling_rate[
    recycling_rate["TIME_PERIOD"] == 2024
].copy()

recycling_rate_2024.shape

(25, 19)

In [176]:
recycling_rate_eu27_2024 = recycling_rate_2024[
    recycling_rate_2024["geo"].isin(eu27)
].copy()

recycling_rate_eu27_2024.shape

(20, 19)

In [177]:
#handling missing data

missing_recycling_countries = set(eu27) - set(recycling_rate_eu27_2024["geo"])

missing_recycling_countries

{'AT', 'BG', 'CZ', 'EL', 'IE', 'IT', 'RO'}

In [179]:
# Need to create a dataset that uses theblatest available value up to 2024 for every EU country.

recycling_rate_eu27_all = recycling_rate[
    recycling_rate["geo"].isin(eu27) & (recycling_rate["TIME_PERIOD"] <= 2024)
].copy()

#Newest year first

recycling_rate_eu27_all = recycling_rate_eu27_all.sort_values(["geo", "TIME_PERIOD"], ascending=[True, False]).reset_index(drop=True)

recycling_rate_latest = recycling_rate_eu27_all.drop_duplicates(subset=["geo"], keep="first").reset_index(drop=True)

recycling_rate_latest.shape

(27, 19)

In [180]:
recycling_rate_latest[
    ["geo",
     "Geopolitical entity (reporting)",
     "TIME_PERIOD",
     "OBS_VALUE"]
].sort_values("TIME_PERIOD")

   geo Geopolitical entity (reporting)  TIME_PERIOD  OBS_VALUE
0   AT                         Austria         2023       62.8
2   BG                        Bulgaria         2023       16.7
4   CZ                         Czechia         2023       43.5
8   EL                          Greece         2023       17.4
15  IT                           Italy         2023       50.8
14  IE                         Ireland         2023       41.9
23  RO                         Romania         2023       12.4
3   CY                          Cyprus         2024       15.8
7   EE                         Estonia         2024       36.4
6   DK                         Denmark         2024       46.4
5   DE                         Germany         2024       66.9
9   ES                           Spain         2024       42.5
11  FR                          France         2024       40.9
10  FI                         Finland         2024       47.9
13  HU                         Hungary         2024       33.6
1   BE                         Belgium         2024       56.2
12  HR                         Croatia         2024       36.7
16  LT                       Lithuania         2024       52.5
18  LV                          Latvia         2024       52.7
17  LU                      Luxembourg         2024       57.3
19  MT                           Malta         2024       16.7
20  NL                     Netherlands         2024       58.0
21  PL                          Poland         2024       31.1
22  PT                        Portugal         2024       32.8
24  SE                          Sweden         2024       46.1
25  SI                        Slovenia         2024       62.4
26  SK                        Slovakia         2024       50.7

In [182]:
recycling_rate_clean = recycling_rate_latest[[
    "geo",
    "Geopolitical entity (reporting)",
    "TIME_PERIOD",
    "OBS_VALUE"
]].copy()

recycling_rate_clean = recycling_rate_clean.rename(columns={
     "geo": "country_code",
     "Geopolitical entity (reporting)": "country_name",
     "TIME_PERIOD": "year",
     "OBS_VALUE": "municipal_recycling_rate"
})

In [184]:
recycling_rate_clean = (recycling_rate_clean.sort_values("country_name").reset_index(drop=True))

recycling_rate_clean.isnull().sum()

country_code                0
country_name                0
year                        0
municipal_recycling_rate    0
dtype: int64

In [185]:
eqli_data = pd.merge(
    eqli_data,
    recycling_rate_clean[["country_code", "municipal_recycling_rate"]],
    on="country_code",
    how="inner"
)

eqli_data.shape

(27, 17)

In [186]:
recycling_rate_clean.to_csv("../data/processed/recycling_rate_latest.csv", index=False)

eqli_data.to_csv(
    "../data/processed/eqli_master.csv",
    index=False
)