In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
indicators = pd.DataFrame({
    "sub_index": [
        "Economic", "Economic", "Economic",
        "Health", "Health", "Health",
        "Education", "Education", "Education",
        "Environment", "Environment", "Environment",
        "Living Conditions", "Living Conditions", "Living Conditions"
    ],
    
    "indicator": [
        "GDP per capita in PPS",
        "Employment rate",
        "At-risk-of-poverty rate",
        
        "Life expectancy at birth",
        "Healthy life years",
        "Self-perceived good or very good health",
        
        "Tertiary education attainment",
        "Early leavers from education and training",
        "Employment rate of recent graduates",
        
        "Renewable energy share",
        "Recycling rate of municipal waste",
        "Pollution, grime or environmental problems",
        
        "Housing cost overburden",
        "Household internet access",
        "Overall life satisfaction"
    ],
    
    "direction": [
        "positive", "positive", "negative",
        "positive", "positive", "positive",
        "positive", "negative", "positive",
        "positive", "positive", "negative",
        "negative", "positive", "positive"
    ]
})
indicators

            sub_index                                   indicator direction
0            Economic                       GDP per capita in PPS  positive
1            Economic                             Employment rate  positive
2            Economic                     At-risk-of-poverty rate  negative
3              Health                    Life expectancy at birth  positive
4              Health                          Healthy life years  positive
5              Health     Self-perceived good or very good health  positive
6           Education               Tertiary education attainment  positive
7           Education   Early leavers from education and training  negative
8           Education         Employment rate of recent graduates  positive
9         Environment                      Renewable energy share  positive
10        Environment           Recycling rate of municipal waste  positive
11        Environment  Pollution, grime or environmental problems  negative
12  Living Conditions                     Housing cost overburden  negative
13  Living Conditions                   Household internet access  positive
14  Living Conditions                   Overall life satisfaction  positive

In [4]:
gdp = pd.read_csv("../data/raw/gdp_per_capita_pps.csv")

gdp.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,indic_ppp,Purchasing power parities indicator,ppp_cat18,Analytical categories for purchasing power parities (PPPs) calculation (based on COICOP18),geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,AL,Albania,2014,NaN,30,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,AL,Albania,2015,NaN,30,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,AL,Albania,2016,NaN,30,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,AL,Albania,2017,NaN,30,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,AL,Albania,2018,NaN,30,NaN,NaN,NaN,NaN,NaN

In [7]:
gdp_2024 = gdp[gdp["TIME_PERIOD"] == 2024].copy()

gdp_2024.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,indic_ppp,Purchasing power parities indicator,ppp_cat18,Analytical categories for purchasing power parities (PPPs) calculation (based on COICOP18),geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
10,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,AL,Albania,2024,NaN,42,NaN,NaN,NaN,NaN,NaN
22,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,AT,Austria,2024,NaN,119,NaN,NaN,NaN,NaN,NaN
34,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,BA,Bosnia and Herzegovina,2024,NaN,37,NaN,NaN,NaN,NaN,NaN
46,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,BE,Belgium,2024,NaN,117,NaN,NaN,NaN,NaN,NaN
58,dataflow,ESTAT:TEC00114(1.0),GDP per capita in PPS,A,Annual,VI_PPS_EU27_2020_HAB,Volume indices of real expenditure per capita ...,GDP,Gross domestic product,BG,Bulgaria,2024,NaN,66,NaN,NaN,NaN,NaN,NaN

In [10]:
gdp_2024[[
    "geo",
    "Geopolitical entity (reporting)",
    "TIME_PERIOD",
    "OBS_VALUE"
]].head(15)

      geo        Geopolitical entity (reporting)  TIME_PERIOD  OBS_VALUE
10     AL                                Albania         2024         42
22     AT                                Austria         2024        119
34     BA                 Bosnia and Herzegovina         2024         37
46     BE                                Belgium         2024        117
58     BG                               Bulgaria         2024         66
70     CH                            Switzerland         2024        157
82     CY                                 Cyprus         2024         99
94     CZ                                Czechia         2024         90
106    DE                                Germany         2024        116
118    DK                                Denmark         2024        127
130  EA19  Euro area - 19 countries  (2015-2022)         2024        105
142  EA20   Euro area – 20 countries (2023-2025)         2024        104
154  EA21   Euro area – 21 countries (from 2026)         2024        104
166    EE                                Estonia         2024         79
178    EL                                 Greece         2024         68

In [11]:
eu27 = [
    "AT", "BE", "BG", "HR", "CY", "CZ", "DK",
    "EE", "FI", "FR", "DE", "EL", "HU", "IE",
    "IT", "LV", "LT", "LU", "MT", "NL", "PL",
    "PT", "RO", "SK", "SI", "ES", "SE"
]

In [9]:
gdp_2024.shape

(43, 19)

In [6]:
gdp.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency',
       'indic_ppp', 'Purchasing power parities indicator', 'ppp_cat18',
       'Analytical categories for purchasing power parities (PPPs) calculation (based on COICOP18)',
       'geo', 'Geopolitical entity (reporting)', 'TIME_PERIOD', 'Time',
       'OBS_VALUE', 'Observation value', 'OBS_FLAG',
       'Observation status (Flag) V2 structure', 'CONF_STATUS',
       'Confidentiality status (flag)'],
      dtype='str')